### ISSUE TITLE
Warning suppression macros conflict with those provided by ign-cmake

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-utils#9]
Both `ign-utils` and `ign-cmake` define macros with the same name, such as `IGN_UTILS_WARN_IGNORE__NON_VIRTUAL_DESTRUCTOR` and `DETAIL_IGN_UTILS_WARN_IGNORE__NON_VIRTUAL_DESTRUCTOR`:

* https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.6.2/include/ignition/utilities/SuppressWarning.hh
* https://github.com/ignitionrobotics/ign-utils/blob/main/include/ignition/utils/SuppressWarning.hh

these header files have different header guards, though, leading to compiler warnings on windows if both are included together:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-pr_any-windows7-amd64&build=1908)](https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1908/) https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1908/msbuild/new/

Perhaps we need to wrap all our `#define` statements in `#ifndef`?

**Comment by chapulina** [comment]
> Perhaps we need to wrap all our #define statements in #ifndef?

+1

**Comment by azeey** [comment]
I was wondering why the warning didn't show up on Linux. It turns out the warning is emitted if the definitions are different. On Linux they are the same, but on windows, ign-cmake has
```c++
#define DETAIL_IGN_UTILS_WARN_IGNORE__NON_VIRTUAL_DESTRUCTOR \
  DETAIL_IGN_UTILS_BEGIN_WARNING_SUPPRESSION(4265) \
  DETAIL_IGN_UTILS_BEGIN_WARNING_SUPPRESSION(5205)
```
while ign-utils has
```c++
#define DETAIL_IGN_UTILS_WARN_IGNORE__NON_VIRTUAL_DESTRUCTOR \
  DETAIL_IGN_UTILS_BEGIN_WARNING_SUPPRESSION(4265)
```

I can add the `#ifndef`, but I'm not sure how we deal with different versions of the macro in two places going forward. It seems like it would lead to confusion. Changing the macro names might be better.

**Comment by chapulina** [comment]
> while ign-utils has

In this case, I think 5205 could be added to `ign-utils`'s macros.

> Changing the macro names might be better.

+1

**Comment by chapulina** [comment]
Addressed in #10

**Comment by scpeters** [comment]
> In this case, I think 5205 could be added to `ign-utils`'s macros.

I think it would make sense to do this as well

**Comment by scpeters** [comment]
> > In this case, I think 5205 could be added to `ign-utils`'s macros.
> 
> I think it would make sense to do this as well

#11
